# Generated by Django 2.2.2 on 2019-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='votes_against',
            field=models.BigIntegerField(default=0, verbose_name='Votes against'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='votes_for',
            field=models.BigIntegerField(default=0, verbose_name='Votes for'),
        ),
    ]
