# Generated by Django 2.2.2 on 2019-06-17 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('cities', '0011_auto_20180108_0706'),
        ('initiative', '0002_auto_20190615_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='city',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='country',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='level',
        ),
        migrations.AddField(
            model_name='initiative',
            name='place_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='initiative',
            name='place_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AddField(
            model_name='initiative',
            name='place_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.District'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='place_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Region'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='place_subregion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Subregion'),
        ),
    ]
