# Generated by Django 2.2.2 on 2019-06-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_initiativeversion_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativelanguage',
            name='last_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initiative.InitiativeVersion'),
        ),
    ]
