# Generated by Django 2.2.2 on 2019-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0004_initiativelanguage_last_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeversion',
            name='categories',
        ),
        migrations.AddField(
            model_name='initiative',
            name='categories',
            field=models.ManyToManyField(to='initiative.InitiativeCategory'),
        ),
    ]
