# Generated by Django 2.2.2 on 2019-06-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0005_auto_20190618_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativelanguage',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='initiative.Initiative'),
        ),
        migrations.AlterField(
            model_name='initiativeversion',
            name='initiative_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='initiative.InitiativeLanguage'),
        ),
    ]
