# Generated by Django 2.2.2 on 2019-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0006_auto_20190629_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeversion',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
