# Generated by Django 2.2.2 on 2019-06-30 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiative', '0007_initiativeversion_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='votes_against_being_spam',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='votes_for_being_spam',
        ),
        migrations.AddField(
            model_name='initiativeversion',
            name='votes_against_being_spam',
            field=models.ManyToManyField(related_name='voters_against_being_spam', to=settings.AUTH_USER_MODEL, verbose_name='Votes against being SPAM'),
        ),
        migrations.AddField(
            model_name='initiativeversion',
            name='votes_for_being_spam',
            field=models.ManyToManyField(related_name='voters_for_being_spam', to=settings.AUTH_USER_MODEL, verbose_name='Votes for being SPAM'),
        ),
    ]
