# Generated by Django 2.2.2 on 2020-01-30 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0008_auto_20190630_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeversion',
            name='votes_against_being_spam',
            field=models.ManyToManyField(blank=True, related_name='voters_against_being_spam', to=settings.AUTH_USER_MODEL, verbose_name='Votes against being SPAM'),
        ),
        migrations.AlterField(
            model_name='initiativeversion',
            name='votes_for_being_spam',
            field=models.ManyToManyField(blank=True, related_name='voters_for_being_spam', to=settings.AUTH_USER_MODEL, verbose_name='Votes for being SPAM'),
        ),
    ]
