# Generated by Django 2.2.2 on 2019-06-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('level', models.SmallIntegerField(verbose_name='Initiative level')),
                ('title', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('outcome', models.TextField()),
                ('votes_for', models.BigIntegerField(verbose_name='Votes for')),
                ('votes_against', models.BigIntegerField(verbose_name='Votes against')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Attached image')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive.Initiative')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Attached file')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive.Initiative')),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='categories',
            field=models.ManyToManyField(to='incentive.InitiativeCategory'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentive.City'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentive.Country'),
        ),
    ]
